asyncapi: 3.0.0
info:
  title: Order API
  version: 1.0.0
servers:
  wsServer:
    host: 'ws://localhost:8080'
    protocol: ws
    description: Websocket server
channels:
  NewOrderPlaced:
    address: new-orders
    servers:
      - $ref: '#/servers/wsServer'
    messages:
      placeOrder.message:
        $ref: '#/components/messages/OrderRequest'
  OrderInitiated:
    address: wip-orders
    servers:
      - $ref: '#/servers/wsServer'
    messages:
      processOrder.message:
        $ref: '#/components/messages/Order'
  OrderCancellationRequested:
    address: to-be-cancelled-orders
    servers:
      - $ref: '#/servers/wsServer'
    messages:
      cancelOrder.message:
        $ref: '#/components/messages/CancelOrderRequest'
  OrderCancelled:
    address: cancelled-orders
    servers:
      - $ref: '#/servers/wsServer'
    messages:
      processCancellation.message:
        $ref: '#/components/messages/CancellationReference'
  OrderAccepted:
    address: accepted-orders
    servers:
      - $ref: '#/servers/wsServer'
    messages:
      orderAccepted.message:
        $ref: '#/components/messages/OrderAccepted'
  OrderDeliveryInitiated:
    address: out-for-delivery-orders
    servers:
      - $ref: '#/servers/wsServer'
    messages:
      orderDeliveryInitiation.message:
        $ref: '#/components/messages/OutForDelivery'
operations:
  placeOrder:
    action: receive
    channel:
      $ref: '#/channels/NewOrderPlaced'
    messages:
      - $ref: '#/channels/NewOrderPlaced/messages/placeOrder.message'
    reply:
      channel:
        $ref: '#/channels/OrderInitiated'
      messages:
        - $ref: '#/channels/OrderInitiated/messages/processOrder.message'
  cancelOrder:
    action: receive
    channel:
      $ref: '#/channels/OrderCancellationRequested'
    messages:
      - $ref: '#/channels/OrderCancellationRequested/messages/cancelOrder.message'
    reply:
      channel:
        $ref: '#/channels/OrderCancelled'
      messages:
        - $ref: '#/channels/OrderCancelled/messages/processCancellation.message'
  orderAccepted:
    action: send
    channel:
      $ref: '#/channels/OrderAccepted'
    messages:
      - $ref: '#/channels/OrderAccepted/messages/orderAccepted.message'
  initiateOrderDelivery:
    action: receive
    channel:
      $ref: '#/channels/OrderDeliveryInitiated'
    messages:
      - $ref: '#/channels/OrderDeliveryInitiated/messages/orderDeliveryInitiation.message'
components:
  messages:
    OrderRequest:
      name: OrderRequest
      title: An order request
      contentType: application/json
      headers:
        type: object
        properties:
          orderCorrelationId:
            type: string
            description: Unique identifier for the request
      correlationId:
        $ref: "#/components/correlationIds/orderCorrelationId"
      payload:
        type: object
        required:
          - id
          - orderItems
        properties:
          id:
            type: integer
          orderItems:
            type: array
            items:
              type: object
              properties:
                id:
                  type: integer
                name:
                  type: string
                quantity:
                  type: integer
                price:
                  type: number
              required:
                - id
                - name
                - quantity
                - price
      examples:
        - name: NEW_ORDER
          headers:
            orderCorrelationId: 12345
          payload:
            id: 10
            orderItems:
              - id: 1
                name: Macbook
                quantity: 1
                price: 2000
              - id: 2
                name: Iphone
                quantity: 1
                price: 1000
    Order:
      name: OrderToProcess
      title: An order that needs to be processed
      contentType: application/json
      headers:
        type: object
        properties:
          orderCorrelationId:
            type: string
            description: Unique identifier for the request
      correlationId:
        $ref: "#/components/correlationIds/orderCorrelationId"
      payload:
        type: object
        required:
          - id
          - totalAmount
          - status
        properties:
          id:
            type: integer
          totalAmount:
            type: number
          status:
            $ref: '#/components/messages/OrderStatus'
      examples:
        - name: NEW_ORDER
          headers:
            orderCorrelationId: 12345
          payload:
            id: 10
            totalAmount: 3000
            status: INITIATED
    CancelOrderRequest:
      name: CancelOrderRequest
      title: A cancel order request
      contentType: application/json
      headers:
        type: object
        properties:
          orderCorrelationId:
            type: string
            description: Unique identifier for the request
      correlationId:
        $ref: "#/components/correlationIds/orderCorrelationId"
      payload:
        type: object
        required:
          - id
        properties:
          id:
            type: integer
      examples:
        - name: CANCEL_ORDER
          headers:
            orderCorrelationId: 12345
          payload:
            id: 10
    CancellationReference:
      name: CancellationReference
      title: A cancellation reference in response to a cancel order request
      contentType: application/json
      headers:
        type: object
        properties:
          orderCorrelationId:
            type: string
            description: Unique identifier for the request
      correlationId:
        $ref: "#/components/correlationIds/orderCorrelationId"
      payload:
        type: object
        required:
          - reference
          - status
        properties:
          reference:
            type: integer
          status:
            $ref: '#/components/messages/OrderStatus'
      examples:
        - name: CANCEL_ORDER
          headers:
            orderCorrelationId: 12345
          payload:
            reference: 10
            status: CANCELLED
    OrderAccepted:
      name: OrderAccepted
      title: Order accepted by Warehouse
      contentType: application/json
      payload:
        type: object
        properties:
          id:
            type: integer
          status:
            $ref: '#/components/messages/OrderStatus'
          timestamp:
            type: string
        required:
          - id
          - status
          - timestamp
      examples:
        - name: ACCEPT_ORDER
          payload:
            id: 123
            status: ACCEPTED
            timestamp: "2025-04-12T14:30:00Z"
    OutForDelivery:
      name: OutForDelivery
      title: Order is out for delivery
      contentType: application/json
      payload:
        type: object
        required:
          - orderId
          - deliveryAddress
          - deliveryDate
        properties:
          orderId:
            type: integer
          deliveryAddress:
            type: string
          deliveryDate:
            type: string
            format: date
      examples:
        - name: ORDER_OUT_FOR_DELIVERY
          payload:
            orderId: 123
            deliveryAddress: "1234 Elm Street, Springfield"
            deliveryDate: "2025-04-14"
    OrderStatus:
      name: OrderStatus
      title: Order status
      payload:
        type: string
        enum:
          - PENDING
          - INITIATED
          - ACCEPTED
          - SHIPPED
          - DELIVERED
          - CANCELLED

  correlationIds:
    orderCorrelationId:
      location: '$message.header#/orderCorrelationId'
